### ISSUE TITLE
`make test-kv` fails locally, but hard to understand why

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1448]
This is what I get running `make test-kv` on `main`:

```
~/github/spin [main|⚑ 1] 
09:12 $ make test-kv
RUST_LOG=spin=trace cargo test --test spinup_tests --features e2e-tests --no-fail-fast -- spinup_tests::key_value_works --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.36s
     Running tests/spinup_tests.rs (target/debug/deps/spinup_tests-7b263268d6339070)

running 1 test
thread 'spinup_tests::key_value_works' panicked at 'called `Result::unwrap()` on an `Err` value: assertion failed: `(left == right)`
  left: `200`,
 right: `500`', tests/testcases/mod.rs:53:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test spinup_tests::key_value_works ... FAILED

failures:

failures:
    spinup_tests::key_value_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 20 filtered out; finished in 2.27s

error: test failed, to rerun pass `--test spinup_tests`
error: 1 target failed:
    `--test spinup_tests`
make: *** [Makefile:64: test-kv] Error 101
```

(Yes, I am working on KV at the moment and so my initial assumption was that I had broken it.  But this happens on clean main without any of my changes.)

Presumably one of the ensures in the HTTP handler is failing, but it's not clear to me how to diagnose the problem.  It would be good to provide at least core diagnostics in failure cases.

**Comment by rajatjindal** [comment]
hmm this is strange, it works for me.

ensured i am on latest commit

```
git --no-pager log -1

commit ab801b04803d4ecdc1ffa57f423ce3e3c1c2234a (HEAD -> main, upstream/main, origin/main, origin/HEAD)
Merge: 033c3d1 5739969
Author: itowlson <ivan.towlson@fermyon.com>
Date:   Fri May 5 11:49:59 2023 +1200

    Merge pull request #1442 from itowlson/kv-local-init
    
    Add `spin up --key-value` option
```



```
make test-kv
.
.
.
.
.

running 1 test
test spinup_tests::key_value_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 19 filtered out; finished in 1.15s

```

The above is from my M2 laptop. I am just trying this on my Intel mac to confirm.

**Comment by rajatjindal** [comment]
works on my intel laptop too:

```
 git --no-pager log -1
commit ab801b04803d4ecdc1ffa57f423ce3e3c1c2234a (HEAD -> main, upstream/main, origin/main, origin/HEAD)
Merge: 033c3d1 5739969
Author: itowlson <ivan.towlson@fermyon.com>
Date:   Fri May 5 11:49:59 2023 +1200

    Merge pull request #1442 from itowlson/kv-local-init
    
    Add `spin up --key-value` option

```


```
make test-kv
running 1 test
test spinup_tests::key_value_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 20 filtered out; finished in 15.40s
```

**Comment by lann** [comment]
I get a different error:

```console
$ make test-kv
running 1 test
thread 'spinup_tests::key_value_works' panicked at 'called `Result::unwrap()` on an `Err` value: running app

Caused by:
    error running spin up.
    stdout []
    stderr: ["Error: Cannot read manifest file from \"/home/lann/f/spin/tests/testcases/key-value/spin.toml\"", "", "Caused by:", "    unknown field `key_value_stores`"]
    ', tests/testcases/mod.rs:53:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test spinup_tests::key_value_works ... FAILED

failures:

failures:
    spinup_tests::key_value_works

**Comment by lann** [comment]
The problem is that the e2e-tests run `spin` via hard-coded command shell (powershell or bash). I normally use `zsh` and my bash config doesn't have a PATH that points at a recent `spin`, so the tests are using some old revision.

**Comment by lann** [comment]
I think if we built `spin` with `cargo install` it would end up in the PATH.

**Comment by rajatjindal** [comment]
We may not want that though? Atleast not implicitly. As it may surprise user by replacing their expected version of spin.

**Comment by lann** [comment]
How about a env var like `SPIN_BIN_PATH` which can be used if set but if not set we run `cargo isntall`?

**Comment by lann** [comment]
`cargo` might add `~/.cargo/bin` to the front of `PATH`; not sure.

**Comment by rajatjindal** [comment]
how about this: `PATH=$SPIN_BIN_PATH:target/debug:target/release:$HOME/.cargo/bin:$PATH`

Note: I have exchanged position of `target/debug` and `target/release`

**Comment by lann** [comment]
Whatever works!

**Comment by itowlson** [comment]
The issue for me is not so much that it failed (though that is vexing) but that the test _does not give me any clue why it failed_.  I will have a look at whether the error comes back in the 500 response body and if so whether we can present it in the assertion message.

(For what it's worth, I don't have a `spin` in `.cargo/bin` and the one on my path is freshly built.  My PATH already includes `target/debug`.)

**Comment by itowlson** [comment]
For the record, the reason for failure was `Condition failed: `&["bar".to_owned()] as &[_] == &store.get_keys()?`.  Adding some more diagnostics to _that_ showed that my attempt to test injecting keys left persistent state in the store, which fouled this test even though I reverted the code.  I will raise a separate issue to use a fresh (or at least predictable) store each time.

**Comment by rylev** [comment]
It would be really nice if we could get the tests to run without requiring any state on the dev machine to be present. I'm not sure I understand the status quo 100%, but ultimately we want the tests to exercise the locally built spin, and the best way to ensure that is to use an absolute path to the right executable instead of trying to get that executable to be available in the PATH.

**Comment by itowlson** [comment]
This issue has kind of developed into I think three separate ones:

1. Need more info about why test failed - fixed via #1457 
2. Need test runs to start from a clean/known state - tracked in #1458, in progress at #1461
3. Make sure to test with the appropriate version of Spin - possibly tracked in #1422, but some comments imply there is more to it than that???

Is there anything else we need to capture, either on those issues/PRs or as new issues?  If not, I will close this.

**Comment by rajatjindal** [comment]
I think your comment covers all issues discussed in this issue and thanks to your reviews, we are close to getting `clean up state dir` issue closed. 

But I am still not 100% sure of what the best path forward is for `add spin to path`. 

@rylev, would adding a new environment variable `SPIN_TEST_BINARY` that overrides everything else on PATH is reasonable? or we should **only** use `SPIN_TEST_BINARY` and if it is not set, exit out of e2e tests (to avoid false negatives)

**Comment by itowlson** [comment]
@rajatjindal If we have a specific outstanding problem around "what is the best way to add Spin to the path for tests" then I suggest create a GH issue specifically for that, with a title that represents it - the title of this PR will not, I think, help anyone find that discussion.  (It would be great if you could do that because I don't understand the issue!  But I'm happy to do it if you are pressed for time.)

**Comment by itowlson** [comment]
@rajatjindal bump re capturing the "add Spin to path" issue (so we can close this)

**Comment by itowlson** [comment]
@rajatjindal Re-bump re capturing the "add Spin to path" issue.  If the problem discussed in the side thread above it still a problem, could you either:

* confirm that #1422 covers it; or
* create an issue for it

please, so we can close this?  Thanks!

**Comment by rajatjindal** [comment]
Hi Ivan, i will check this and get back to you. Sorry for the delay

**Comment by itowlson** [comment]
@rajatjindal re-bump.  To be clear, I don't need to know if the issue is fixed - I just need to know that any info you need from this thread has been captured elsewhere please?  If you're not sure maybe create a new issue?

**Comment by rajatjindal** [comment]
Hi @itowlson i am working on this as part of https://github.com/fermyon/spin/pull/1422, and there are actually two issues for it https://github.com/fermyon/spin/issues/1385 and https://github.com/fermyon/spin/issues/1400

so i think we can close this specific issue. 

apologies for the delay in responding.

**Comment by itowlson** [comment]
No worries, thanks!
